linters-settings:
  dupl:
    threshold: 200
  funlen:
    lines: 100
    statements: 60
  goconst:
    min-len: 3
    min-occurrences: 5
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/icdb37/kypd
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 160
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  errcheck:
    check-blank: true
    check-type-assertions: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-use-default: false
  exclude-dirs:
    - "tmp"
  exclude:
    - "TODO" # 排除包含 TODO 的注释
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    - path: _mock\.go
      linters:
        - revive
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
  max-same-issues: 0

run:
  timeout: 3m
  issues-exit-code: 1
